dist: trusty
sudo: required

language: cpp

compiler: gcc

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - build-essential
            - libglm-dev
            - libglew-dev
            - freeglut3-dev
            - cmake
            - g++-7
            - gcc-7

script:
    - cmake .
    - make
