language: cpp

compiler: gcc

addons:
    apt:
        packages:
            - build-essential
            - libglm-dev
            - libglew-dev
            - freeglut3-dev
            - cmake
            - g++-6

script:
    - cmake .
    - make
