version: 2

general:
  branches:
    only:
      - circleci

jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: interactive_computer_graphics
          command: echo Will get this working.
